#---------- Postgres ----------#

development:
  adapter: postgresql
  encoding: unicode
  database: ellipsis_olm
  pool: 5
  username: postgres
  password: h4rdc0r3
  host: db  # Alterado de localhost para o nome do serviço no Docker
  port: 5432  # Adicionado o número da porta padrão do PostgreSQL

test:
  adapter: postgresql
  encoding: unicode
  database: ellipsis_test
  pool: 5
  username: postgres
  password: h4rdc0r3
  host: db  # Alterado de localhost para o nome do serviço no Docker
  port: 5432  # Adicionado o número da porta padrão do PostgreSQL