default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: h4rdc0r3
  host: localhost   # Alterado de "db" para "localhost"
  port: 5432

development:
  <<: *default
  database: ellipsis_olm

test:
  <<: *default
  database: ellipsis_test